fnum = int(input("Give me the first number: "))
snum = int(input("Give me the second number: "))
print("Thank you!")
print(f"{fnum} + {snum} = {fnum+snum}")
print(f"{fnum} - {snum} = {fnum-snum}")
print(f"{fnum} / {snum} = {fnum / snum:.0f}")
print(f"{fnum} * {snum} = {fnum*snum}")
